language: node_js
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- '6'
before_script:
- npm install -g bower polymer-cli firebase-tools
- bower install
script:
- "./travis_scripts/firebase_generate_config.sh > scripts/config.js"
- xvfb-run npm test
- polymer build --bundle --js-minify --css-minify --html-minify
after_success:
- firebase deploy --token=${FIREBASE_API_TOKEN}
notifications:
  email: false